name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
      with: 
        submodules: 'recursive'
    - name: Make directory and change into it
      run: mkdir build && cd build
    - name: CMake Configure Step
      run: cmake ../pymeshview
    - name: CMake Build Step
      run: cmake --build .
